version: "3"
services:
  frontend: # 이름은 어떤걸로 지정해도 상관없음
    build:
      dockerfile: Dockerfile # dockerfile이름
      context: ./ # 도커파일 위치 명시
    volumes:
      - /app/node_modules #도커 /app/node_modules는 맵핑을 따로 안해주겠다.
      - ./:/app # 로컬에 있는 모든 파일을 맵핑
    ports:
      - "3001:3001" # port 맵핑
    stdin_open: true
