version: "3.2"

services:
  app:
    build:
      context: ./app
    volumes:
      - log-data:/app/logs
    ports:
      - "8080:8080"

  filebeat:
    build:
      context: ./filebeat
    volumes:
      - log-data:/var/log/server
    networks:
      - elk
    depends_on:
      - logstash

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
  log-data:
