name: Upload Website

on:
  push:
    branches: [ feature ]
    
defaults:
  run:
    working-directory: front-end
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: happyhouse-guide.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'build'
          DEST_DIR: '/'
